apiVersion: v1
kind: Pod
metadata:
  labels:
    citype: jenkins-declarative-pipeline
spec:
  containers:
  - name: dind
    image: docker:19.03.12-dind
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
