apiVersion: v1
kind: Pod
metadata:
  labels:
    citype: jenkins-declarative-pipeline
spec:
  containers:
  - name: scoutsuite
    image: quay.io/molu8bits/scoutsuite:latest
    command:
    - cat
    tty: true
# Uncomment if behind some proxy server
#    env:
#      - name: http_proxy
#        value: "http://myproxy.domain:8080"
#      - name: https_proxy
#        value: "http://myproxy.domain:8080"
#      - name: no_proxy
#        value: "*.internal.domain,localhost,127.0.0.1,192.168.0.1,192.168.0.2"
  - name: awscli
    image: amazon/aws-cli:latest
    command:
    - cat
    tty: true
# Uncomment if behind proxy server
#    env:
#      - name: http_proxy
#        value: "http://myproxy.domain:8080"
#      - name: https_proxy
#        value: "http://myproxy.domain:8080"
#      - name: no_proxy
#        value: "*.internal.domain,localhost,127.0.0.1,192.168.0.1,192.168.0.2"