apiVersion: v1
kind: Pod
metadata:
  labels:
    citype: jenkins-declarative-pipeline
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
  - name: zap2docker
    image: owasp/zap2docker-weekly:latest
    command:
    - cat
    tty: true
# Uncomment if behind proxy server
#    env:
#      - name: http_proxy
#        value: "http://myproxy.domain:8080"
#      - name: https_proxy
#        value: "http://myproxy.domain:8080"
#      - name: no_proxy
#        value: "*.internal.domain,localhost,127.0.0.1,192.168.0.1,192.168.0.2"
